/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.86
 * Generated at: 2024-04-29 02:31:10 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class login_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/bottom.jsp", Long.valueOf(1714091459934L));
    _jspx_dependants.put("/top.jsp", Long.valueOf(1714107916932L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(3);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"ko-kr\">\r\n");
      out.write("<head>\r\n");
      out.write("	<meta charset=\"utf-8\">\r\n");
      out.write("	<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("	<title>Main</title>\r\n");
      out.write("	<link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css\" rel=\"stylesheet\" integrity=\"sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH\" crossorigin=\"anonymous\">\r\n");
      out.write("	<link rel=\"stylesheet\" href=\"https://cdn.jsdelivr.net/npm/bootstrap-icons@1.7.1/font/bootstrap-icons.css\">\r\n");
      out.write("	<style type=\"text/css\">\r\n");
      out.write("		body{\r\n");
      out.write("			font-family: \"나눔스퀘어 네오\";\r\n");
      out.write("		}\r\n");
      out.write("	</style>\r\n");
      out.write("	\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<div class=\"container w-75\">\r\n");
      out.write("	<!-- nav top -->\r\n");
      out.write("	<header class=\"py-3\">\r\n");
      out.write("		<div class=\"container d-flex flex-wrap justify-content-center\">\r\n");
      out.write("			<!-- 로고 -->\r\n");
      out.write("			<a href=\"main.jsp\"\r\n");
      out.write("				class=\"d-flex align-items-center mb-3 mb-lg-0 me-lg-auto link-body-emphasis text-decoration-none\">\r\n");
      out.write("				<img src=\"resource/icon/tree-solid.svg\" width=\"30\" height=\"30\"> \r\n");
      out.write("				<span class=\"fs-4\">어쩌다산책</span>\r\n");
      out.write("			</a>\r\n");
      out.write("			<!-- 검색 -->\r\n");
      out.write("				<form class=\"d-flex\" role=\"search\">\r\n");
      out.write("					<input class=\"form-control me-2\" type=\"search\" placeholder=\"검색\"\r\n");
      out.write("						aria-label=\"Search\">\r\n");
      out.write("					<button type=\"submit\">\r\n");
      out.write("						<i class=\"bi bi-search\"></i>\r\n");
      out.write("					</button>\r\n");
      out.write("				</form>\r\n");
      out.write("			</div>\r\n");
      out.write("	</header>\r\n");
      out.write("	\r\n");
      out.write("	<!-- nav bottom -->\r\n");
      out.write("	<nav class=\"py-2  border-bottom\">\r\n");
      out.write("		<div class=\"container d-flex flex-wrap\">\r\n");
      out.write("			<ul class=\"nav me-auto\">\r\n");
      out.write("				<li class=\"nav-item\">\r\n");
      out.write("					<a href=\"#\" class=\"nav-link link-body-emphasis px-2\">문학</a>\r\n");
      out.write("				</li>\r\n");
      out.write("				<li class=\"nav-item\">\r\n");
      out.write("					<a href=\"#\" class=\"nav-link link-body-emphasis px-2\">인문 | 사회 | 과학</a>\r\n");
      out.write("				</li>\r\n");
      out.write("				<li class=\"nav-item\">\r\n");
      out.write("					<a href=\"#\" class=\"nav-link link-body-emphasis px-2\">그림책</a>\r\n");
      out.write("				</li>\r\n");
      out.write("				<li class=\"nav-item\">\r\n");
      out.write("					<a href=\"#\" class=\"nav-link link-body-emphasis px-2\">커뮤니티</a>\r\n");
      out.write("				</li>\r\n");
      out.write("			</ul>\r\n");
      out.write("			<ul class=\"nav\">\r\n");
      out.write("				<li class=\"nav-item\"><a href=\"#\"\r\n");
      out.write("					class=\"nav-link link-body-emphasis px-2\">로그인</a></li>\r\n");
      out.write("				<li class=\"nav-item\"><a href=\"#\"\r\n");
      out.write("					class=\"nav-link link-body-emphasis px-2\">회원가입</a></li>\r\n");
      out.write("				<li class=\"nav-item\"><a href=\"#\"\r\n");
      out.write("					class=\"nav-link link-body-emphasis px-2\">마이페이지</a></li>\r\n");
      out.write("				<li class=\"nav-item\"><a href=\"#\"\r\n");
      out.write("					class=\"nav-link link-body-emphasis px-2\">장바구니</a></li>\r\n");
      out.write("			</ul>\r\n");
      out.write("		</div>\r\n");
      out.write("	</nav>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<script src=\"//t1.daumcdn.net/mapjsapi/bundle/postcode/prod/postcode.v2.js\"></script>\r\n");
      out.write("<script src=\"script.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<div class=\"container py-5 px-5\">\r\n");
      out.write("	<h3 align=\"center\">회원가입</h3><br>\r\n");
      out.write("	\r\n");
      out.write("	<div class=\"row d-flex justify-content-center\">\r\n");
      out.write(" 		<div class=\"col-1\">\r\n");
      out.write(" 			<label>아이디</label>\r\n");
      out.write("		</div>\r\n");
      out.write(" 		<div class=\"col-6\">\r\n");
      out.write("			<div class=\"input-group mb-3\">\r\n");
      out.write("				<input type=\"text\" name=\"id\" class=\"form-control\" id=\"\">\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write(" 	<div class=\"row d-flex justify-content-center\">\r\n");
      out.write(" 		<div class=\"col-1\">\r\n");
      out.write(" 			<label>주소</label>\r\n");
      out.write("		</div>\r\n");
      out.write(" 		<div class=\"col-6\">\r\n");
      out.write("			<div class=\"input-group mb-3\">\r\n");
      out.write("				<input type=\"text\" name=\"postcode\" class=\"form-control\" id=\"sample6_postcode\" placeholder=\"우편번호\">\r\n");
      out.write("				<input type=\"button\" onclick=\"sample6_execDaumPostcode()\" value=\"우편번호 찾기\"><br>\r\n");
      out.write("			</div>\r\n");
      out.write("			<div class=\"input-group mb-3\">\r\n");
      out.write("				<input type=\"text\" name=\"adress\" class=\"form-control\" id=\"sample6_address\" placeholder=\"주소\"><br>\r\n");
      out.write("			</div>\r\n");
      out.write("			<div class=\"input-group mb-3\">\r\n");
      out.write("				<input type=\"text\" name=\"detailAddress\" class=\"form-control\" id=\"sample6_detailAddress\" placeholder=\"상세주소\">\r\n");
      out.write("			</div>\r\n");
      out.write("			<div class=\"input-group mb-3\">\r\n");
      out.write("				<input type=\"hidden\" id=\"sample6_extraAddress\" class=\"form-control\" placeholder=\"참고항목\">\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("	\r\n");
      out.write(" 	\r\n");
      out.write("	\r\n");
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	<!-- footer -->\r\n");
      out.write("	<div class=\"container\">\r\n");
      out.write("		<footer class=\"py-5\">\r\n");
      out.write("			<div class=\"row\">\r\n");
      out.write("				<div class=\"col-6 col-md-2 mb-3\">\r\n");
      out.write("					<h5>Section</h5>\r\n");
      out.write("					<ul class=\"nav flex-column\">\r\n");
      out.write("						<li class=\"nav-item mb-2\"><a href=\"#\"\r\n");
      out.write("							class=\"nav-link p-0 text-body-secondary\">Home</a></li>\r\n");
      out.write("						<li class=\"nav-item mb-2\"><a href=\"#\"\r\n");
      out.write("							class=\"nav-link p-0 text-body-secondary\">Features</a></li>\r\n");
      out.write("						<li class=\"nav-item mb-2\"><a href=\"#\"\r\n");
      out.write("							class=\"nav-link p-0 text-body-secondary\">Pricing</a></li>\r\n");
      out.write("						<li class=\"nav-item mb-2\"><a href=\"#\"\r\n");
      out.write("							class=\"nav-link p-0 text-body-secondary\">FAQs</a></li>\r\n");
      out.write("						<li class=\"nav-item mb-2\"><a href=\"#\"\r\n");
      out.write("							class=\"nav-link p-0 text-body-secondary\">About</a></li>\r\n");
      out.write("					</ul>\r\n");
      out.write("				</div>\r\n");
      out.write("\r\n");
      out.write("				<div class=\"col-6 col-md-2 mb-3\">\r\n");
      out.write("					<h5>Section</h5>\r\n");
      out.write("					<ul class=\"nav flex-column\">\r\n");
      out.write("						<li class=\"nav-item mb-2\"><a href=\"#\"\r\n");
      out.write("							class=\"nav-link p-0 text-body-secondary\">Home</a></li>\r\n");
      out.write("						<li class=\"nav-item mb-2\"><a href=\"#\"\r\n");
      out.write("							class=\"nav-link p-0 text-body-secondary\">Features</a></li>\r\n");
      out.write("						<li class=\"nav-item mb-2\"><a href=\"#\"\r\n");
      out.write("							class=\"nav-link p-0 text-body-secondary\">Pricing</a></li>\r\n");
      out.write("						<li class=\"nav-item mb-2\"><a href=\"#\"\r\n");
      out.write("							class=\"nav-link p-0 text-body-secondary\">FAQs</a></li>\r\n");
      out.write("						<li class=\"nav-item mb-2\"><a href=\"#\"\r\n");
      out.write("							class=\"nav-link p-0 text-body-secondary\">About</a></li>\r\n");
      out.write("					</ul>\r\n");
      out.write("				</div>\r\n");
      out.write("\r\n");
      out.write("				<div class=\"col-6 col-md-2 mb-3\">\r\n");
      out.write("					<h5>Section</h5>\r\n");
      out.write("					<ul class=\"nav flex-column\">\r\n");
      out.write("						<li class=\"nav-item mb-2\"><a href=\"#\"\r\n");
      out.write("							class=\"nav-link p-0 text-body-secondary\">Home</a></li>\r\n");
      out.write("						<li class=\"nav-item mb-2\"><a href=\"#\"\r\n");
      out.write("							class=\"nav-link p-0 text-body-secondary\">Features</a></li>\r\n");
      out.write("						<li class=\"nav-item mb-2\"><a href=\"#\"\r\n");
      out.write("							class=\"nav-link p-0 text-body-secondary\">Pricing</a></li>\r\n");
      out.write("						<li class=\"nav-item mb-2\"><a href=\"#\"\r\n");
      out.write("							class=\"nav-link p-0 text-body-secondary\">FAQs</a></li>\r\n");
      out.write("						<li class=\"nav-item mb-2\"><a href=\"#\"\r\n");
      out.write("							class=\"nav-link p-0 text-body-secondary\">About</a></li>\r\n");
      out.write("					</ul>\r\n");
      out.write("				</div>\r\n");
      out.write("\r\n");
      out.write("				<div class=\"col-md-5 offset-md-1 mb-3\">\r\n");
      out.write("					<form>\r\n");
      out.write("						<h5>Subscribe to our newsletter</h5>\r\n");
      out.write("						<p>Monthly digest of what's new and exciting from us.</p>\r\n");
      out.write("						<div class=\"d-flex flex-column flex-sm-row w-100 gap-2\">\r\n");
      out.write("							<label for=\"newsletter1\" class=\"visually-hidden\">Email\r\n");
      out.write("								address</label> <input id=\"newsletter1\" type=\"text\" class=\"form-control\"\r\n");
      out.write("								placeholder=\"Email address\">\r\n");
      out.write("							<button class=\"btn btn-primary\" type=\"button\">Subscribe</button>\r\n");
      out.write("						</div>\r\n");
      out.write("					</form>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("\r\n");
      out.write("			<div\r\n");
      out.write("				class=\"d-flex flex-column flex-sm-row justify-content-between py-4 my-4 border-top\">\r\n");
      out.write("				<p>&copy; 2024 Company, Inc. All rights reserved.</p>\r\n");
      out.write("				<ul class=\"list-unstyled d-flex\">\r\n");
      out.write("					<li class=\"ms-3\"><a class=\"link-body-emphasis\" href=\"#\"><svg\r\n");
      out.write("								class=\"bi\" width=\"24\" height=\"24\">\r\n");
      out.write("								<use xlink:href=\"#twitter\" /></svg></a></li>\r\n");
      out.write("					<li class=\"ms-3\"><a class=\"link-body-emphasis\" href=\"#\"><svg\r\n");
      out.write("								class=\"bi\" width=\"24\" height=\"24\">\r\n");
      out.write("								<use xlink:href=\"#instagram\" /></svg></a></li>\r\n");
      out.write("					<li class=\"ms-3\"><a class=\"link-body-emphasis\" href=\"#\"><svg\r\n");
      out.write("								class=\"bi\" width=\"24\" height=\"24\">\r\n");
      out.write("								<use xlink:href=\"#facebook\" /></svg></a></li>\r\n");
      out.write("				</ul>\r\n");
      out.write("			</div>\r\n");
      out.write("		</footer>\r\n");
      out.write("	</div>\r\n");
      out.write("</div>\r\n");
      out.write("	<script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js\" integrity=\"sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
